

drop table if exists addresses;

drop table if exists users;
drop table if exists survey;
drop table if exists survey_audit;

drop table if exists annual_batch;
drop table if exists gb_batch_items;
drop table if exists ni_batch_item;
drop table if exists quarterly_batch;
drop table if exists monthly_batch;

drop table if exists status_values;
drop table if exists addresses;
drop table if exists export_definitions;

create table status_values
(
    id          int primary key,
    description varchar(255) not null,
    constraint status_values_id_uindex
        unique (id)
);

insert into status_values(id, description)
values (0, 'Not Started');

insert into status_values(id, description)
values (1, 'File Uploaded');

insert into status_values(id, description)
values (2, 'File Reloaded');

insert into status_values(id, description)
values (3, 'Upload Failed');

insert into status_values(id, description)
values (4, 'Successful - Complete');

create table addresses
(
    id                  int identity primary key,
    pcd7                varchar(7)  not null,
    tlec99              varchar(3)  null,
    ELWA                decimal(38) null,
    SCOTER              varchar(6)  null,
    Walespca            decimal(38) null,
    ward03              varchar(6)  null,
    scotpca             decimal(38) null,
    ukpca               decimal(38) null,
    TTWA07              decimal(38) null,
    ttwa08              decimal(38) null,
    pca2010             varchar(3)  null,
    nuts2               varchar(4)  null,
    nuts3               varchar(5)  null,
    nuts4               varchar(7)  null,
    nuts10              varchar(10) null,
    nuts102             varchar(4)  null,
    nuts103             varchar(5)  null,
    nuts104             varchar(7)  null,
    eregn10             varchar(2)  null,
    eregn103            varchar(3)  null,
    NUTS133             varchar(5)  null,
    NUTS132             varchar(4)  null,
    eregn133            varchar(3)  null,
    eregn13             varchar(2)  null,
    DEGURBA             decimal(38) null,
    dzone1              varchar(9)  null,
    dzone2              varchar(9)  null,
    soa1                varchar(9)  null,
    soa2                varchar(9)  null,
    ward05              varchar(6)  null,
    oacode              varchar(10) null,
    urind               decimal(38) null,
    urindsul            decimal(38) null,
    lea                 varchar(3)  null,
    ward98              varchar(6)  null,
    OSLAUA9d            varchar(9)  null,
    ctry9d              varchar(9)  not null,
    casward             varchar(6)  null,
    oa11                varchar(9)  null,
    CTY                 varchar(9)  null,
    LAUA                varchar(9)  null,
    WARD                varchar(9)  null,
    CED                 varchar(9)  null,
    GOR9d               varchar(9)  null,
    PCON9d              varchar(9)  null,
    TECLEC9d            varchar(9)  null,
    TTWA9d              varchar(9)  null,
    lau2                varchar(9)  null,
    PARK                varchar(9)  null,
    LSOA11              varchar(9)  null,
    MSOA11              varchar(9)  null,
    CCG                 varchar(9)  null,
    RU11IND             varchar(2)  null,
    OAC11               varchar(3)  null,
    LEP1                varchar(9)  null,
    LEP2                varchar(9)  null,
    IMD                 decimal(38) null,
    ru11indsul          decimal(38) null,
    NUTS163             varchar(5)  null,
    NUTS162             varchar(4)  null,
    eregn163            varchar(3)  null,
    eregn16             varchar(2)  not null,
    METCTY              varchar(9)  not null,
    UTLA                varchar(9)  not null,
    WIMD2014quintile    decimal(38) null,
    decile2015          decimal(38) null,
    CombinedAuthorities varchar(9)  not null,
);



create table export_definitions
(
    Variables       varchar(10) not null
        primary key,
    Research        tinyint     not null,
    Regional_Client tinyint     not null,
    Government      tinyint     not null,
    Special_License tinyint     not null,
    End_User        tinyint     not null,
    Adhoc           tinyint     not null
);


create table monthly_batch
(
    id          int identity primary key,
    month       int default 0 not null,
    year        int           not null,
    status      int default 0 not null,
    description text          null,
    constraint monthly_batch_status_values_id_fk
        foreign key (status) references status_values (id)
);



create table annual_batch
(
    id          int primary key not null,
    year        int             null,
    status      int             null,
    description text            null,
    constraint annual_batch_status_values_id_fk
        foreign key (status) references status_values (id)
);


create table gb_batch_items
(
    id     int not null primary key,
    year   int null,
    month  int null,
    week   int not null,
    status int null,
    constraint batch
        foreign key (id) references monthly_batch (id),
    constraint gb_batch_items_status_values_id_fk
        foreign key (status) references status_values (id)
);


create table ni_batch_item
(
    id     int not null primary key,
    year   int null,
    month  int null,
    status int null,
    constraint monthly
        foreign key (id) references monthly_batch (id),
    constraint ni_batch_item_status_values_id_fk
        foreign key (status) references status_values (id)
);

create table quarterly_batch
(
    id          int primary key,
    quarter     int  null,
    year        int  null,
    status      int  null,
    description text null,
    constraint qb_to_mb
        foreign key (id) references monthly_batch (id),
    constraint quarterly_batch_status_values_id_fk
        foreign key (status) references status_values (id)
);


create table survey
(
    id            int                 not null,
    file_week     int                 not null,
    file_month    int                 not null,
    file_year     int                 not null,
    file_name     varchar(255)        not null,
    file_source   char(2)             not null,

    Quota         real sparse         null,
    Week          real sparse         null,
    W1Yr          real sparse         null,
    Qrtr          real sparse         null,
    Addr          real sparse         null,
    WavFnd        real sparse         null,
    Hhld          real sparse         null,
    Person        real sparse         null,
    ExpStartInt   real sparse         null,
    ExpEndInt     real sparse         null,
    SurveyYear    varchar(16) sparse  null,
    Year          real sparse         null,
    Month         real sparse         null,
    StageAttempt  varchar(8) sparse   null,
    SurvID        varchar(8) sparse   null,
    SubSample     real sparse         null,
    Quota2        varchar(8) sparse   null,
    AddressKey    varchar(8) sparse   null,
    MO            real sparse         null,
    SampArea      varchar(8) sparse   null,
    OSGridRef     real sparse         null,
    LEA           varchar(8) sparse   null,
    MajorStrat    real sparse         null,
    GOR           real sparse         null,
    Acorn         varchar(8) sparse   null,
    GFFMU         real sparse         null,
    PrevIssSerNo  varchar(16) sparse  null,
    OldSerial     varchar(16) sparse  null,
    PIDNo         varchar(16) sparse  null,
    Rand          varchar(8) sparse   null,
    OSCty         varchar(8) sparse   null,
    OSLAUA        varchar(8) sparse   null,
    OSWard        varchar(8) sparse   null,
    OSHlthAu      varchar(8) sparse   null,
    Ctry          varchar(8) sparse   null,
    PCon          varchar(8) sparse   null,
    TECLEC        varchar(8) sparse   null,
    TTWA          varchar(8) sparse   null,
    PCT           varchar(8) sparse   null,
    NUTS          varchar(16) sparse  null,
    PSED          varchar(8) sparse   null,
    WardC91       varchar(8) sparse   null,
    WardO91       varchar(8) sparse   null,
    Ward98        varchar(8) sparse   null,
    StatsWard     varchar(8) sparse   null,
    OACode        varchar(16) sparse  null,
    CASWard       varchar(8) sparse   null,
    SOA1          varchar(16) sparse  null,
    DZone1        varchar(16) sparse  null,
    SOA2          varchar(16) sparse  null,
    DZone2        varchar(16) sparse  null,
    OAC           varchar(8) sparse   null,
    MOCOUNT       varchar(256) sparse null,
    Attempt       real sparse         null,
    LA            varchar(8) sparse   null,
    SampQtr       real sparse         null,
    HInd          real sparse         null,
    Nurse         real sparse         null,
    CargoH        varchar(8) sparse   null,
    Country       real sparse         null,
    GB            real sparse         null,
    LFSSamp       real sparse         null,
    PCode         varchar(8) sparse   null,
    CID96         varchar(8) sparse   null,
    LAD96         varchar(8) sparse   null,
    WAD96         varchar(8) sparse   null,
    TLEC99        varchar(8) sparse   null,
    PCA           varchar(8) sparse   null,
    Teleph        real sparse         null,
    Train         real sparse         null,
    ThisWv        real sparse         null,
    ThisQtr       real sparse         null,
    LstHO         real sparse         null,
    LstHO4        real sparse         null,
    LstNC         real sparse         null,
    LstRfDt       real sparse         null,
    LstRfDy       real sparse         null,
    LstRfM        varchar(16) sparse  null,
    LstHRPId1     real sparse         null,
    OldSNo        varchar(16) sparse  null,
    OnAddr        real sparse         null,
    Workload      real sparse         null,
    Cont          real sparse         null,
    NewHld        real sparse         null,
    RefDte        real sparse         null,
    RefDay        real sparse         null,
    RefMnth       varchar(16) sparse  null,
    CalWeek       real sparse         null,
    Calqrtr       real sparse         null,
    CalW1YR       real sparse         null,
    IntvNo        real sparse         null,
    Lintnum       real sparse         null,
    RespHH        real sparse         null,
    OldNper       real sparse         null,
    Rels1         varchar(16) sparse  null,
    HHComp        real sparse         null,
    HHNew         real sparse         null,
    Wv1Num        real sparse         null,
    ChkSt         real sparse         null,
    NumPer        real sparse         null,
    PerNo         real sparse         null,
    RelTxt        varchar(16) sparse  null,
    LEstimte      varchar(8) sparse   null,
    HBNow         real sparse         null,
    Sex           real sparse         null,
    Age           real sparse         null,
    HallRes       real sparse         null,
    MarStt        real sparse         null,
    XMarSta       real sparse         null,
    MarSta        real sparse         null,
    MarChk        real sparse         null,
    LivTog        real sparse         null,
    Liv12W        real sparse         null,
    HRPId         real sparse         null,
    Estimate      real sparse         null,
    MarComp12     real sparse         null,
    DVMrDF12      real sparse         null,
    HldCount      real sparse         null,
    HH1           real sparse         null,
    RelTxt2       varchar(16) sparse  null,
    R01           real sparse         null,
    R02           real sparse         null,
    R03           real sparse         null,
    R04           real sparse         null,
    R05           real sparse         null,
    R06           real sparse         null,
    R07           real sparse         null,
    R08           real sparse         null,
    R09           real sparse         null,
    R10           real sparse         null,
    R11           real sparse         null,
    R12           real sparse         null,
    R13           real sparse         null,
    R14           real sparse         null,
    R15           real sparse         null,
    R16           real sparse         null,
    Parent1       real sparse         null,
    NoUnits       real sparse         null,
    AFAM1         real sparse         null,
    ShowFAM       real sparse         null,
    U14kids1      real sparse         null,
    U18kids1      real sparse         null,
    ParentA1      real sparse         null,
    ParentB1      real sparse         null,
    Parent2       real sparse         null,
    NoUnitsSS     real sparse         null,
    FAMUNIT1      real sparse         null,
    ShowFAM2      real sparse         null,
    U14kids2      real sparse         null,
    U18kids2      real sparse         null,
    ParentA2      real sparse         null,
    ParentB2      real sparse         null,
    SSC1          real sparse         null,
    SSCType1      real sparse         null,
    RDay1         real sparse         null,
    RInd1         real sparse         null,
    NDOB1         real sparse         null,
    NumAds        real sparse         null,
    PenFlag       real sparse         null,
    RanDob        real sparse         null,
    DumDob        real sparse         null,
    LonePar1      real sparse         null,
    DVMrDF1       real sparse         null,
    MarComp1      real sparse         null,
    SSC2          real sparse         null,
    SSCType2      real sparse         null,
    Ten1          real sparse         null,
    Tied          real sparse         null,
    LLord         real sparse         null,
    Furn          real sparse         null,
    EndHHInf      real sparse         null,
    Pind          real sparse         null,
    CargoP        varchar(8) sparse   null,
    PersNo        real sparse         null,
    LINow         real sparse         null,
    LIOut         real sparse         null,
    IntNow        real sparse         null,
    IOutDate      varchar(16) sparse  null,
    FamUnit       real sparse         null,
    RespNo        real sparse         null,
    NTNLTY12      real sparse         null,
    NatSpec       varchar(40) sparse  null,
    Nltyspc       varchar(40) sparse  null,
    NatO7         real sparse         null,
    Cry12         real sparse         null,
    CrySpec       varchar(40) sparse  null,
    CryO7         real sparse         null,
    CameYr        real sparse         null,
    ContUK        real sparse         null,
    CameYr2       real sparse         null,
    CameMT        real sparse         null,
    WhyUK10       real sparse         null,
    NatldE111     real sparse         null,
    NatldE112     real sparse         null,
    NatldE113     real sparse         null,
    NatldE114     real sparse         null,
    NatldE115     real sparse         null,
    NatldE116     real sparse         null,
    NatldS111     real sparse         null,
    NatldS112     real sparse         null,
    NatldS113     real sparse         null,
    NatldS114     real sparse         null,
    NatldS115     real sparse         null,
    NatldS116     real sparse         null,
    NatldW111     real sparse         null,
    NatldW112     real sparse         null,
    NatldW113     real sparse         null,
    NatldW114     real sparse         null,
    NatldW115     real sparse         null,
    NatldW116     real sparse         null,
    NatldN111     real sparse         null,
    NatldN112     real sparse         null,
    NatldN113     real sparse         null,
    NatldN114     real sparse         null,
    NatldN115     real sparse         null,
    NatldN116     real sparse         null,
    NatldN117     real sparse         null,
    NatldO        varchar(152) sparse null,
    NatIdCod      real sparse         null,
    CymU          real sparse         null,
    CymS          real sparse         null,
    CymsF         real sparse         null,
    CymR          real sparse         null,
    CymW          real sparse         null,
    Eth11EW       real sparse         null,
    Eth11S        real sparse         null,
    Eth11NI       real sparse         null,
    EthWhe        real sparse         null,
    EthWhW        real sparse         null,
    EthWSC        real sparse         null,
    EthMx11       real sparse         null,
    EthAs11       real sparse         null,
    EthAs11S      real sparse         null,
    EthBl11       real sparse         null,
    EthAFS        real sparse         null,
    EthCBS        real sparse         null,
    EthOth11      varchar(152) sparse null,
    EthDes        varchar(152) sparse null,
    EthOCod       varchar(8) sparse   null,
    ResTme        real sparse         null,
    ResMth        real sparse         null,
    ResBby        real sparse         null,
    M3Cry         real sparse         null,
    M3CrySpec     varchar(40) sparse  null,
    M3CryO        real sparse         null,
    M3Area        varchar(24) sparse  null,
    M3Cty         varchar(24) sparse  null,
    M3ResC        real sparse         null,
    OYEqM3        real sparse         null,
    OYCry         real sparse         null,
    OYCrySpec     varchar(40) sparse  null,
    OYCryO        real sparse         null,
    OYArea        varchar(24) sparse  null,
    OYCty         varchar(24) sparse  null,
    OYResC        real sparse         null,
    Eth02         varchar(48) sparse  null,
    Ethc          real sparse         null,
    SIDFtFQn      real sparse         null,
    SIDTUQn       real sparse         null,
    SIDV          real sparse         null,
    CardNo        real sparse         null,
    ReligE        real sparse         null,
    ReligW        real sparse         null,
    ReligS        real sparse         null,
    RelOth        varchar(152) sparse null,
    RelOcod       real sparse         null,
    Lang          real sparse         null,
    LangD1        real sparse         null,
    LangD2        real sparse         null,
    Intuse        real sparse         null,
    SUBWLLFS      real sparse         null,
    Satis         real sparse         null,
    Worth         real sparse         null,
    Happy         real sparse         null,
    Anxious       real sparse         null,
    SUBPOST       real sparse         null,
    VetServ       real sparse         null,
    VetCurr       real sparse         null,
    VetYrLft1     real sparse         null,
    VtYrLft2      real sparse         null,
    VtYrLft3      real sparse         null,
    VETYEARLFT    real sparse         null,
    VLFT2CHK      real sparse         null,
    Schm12        real sparse         null,
    NewDea10      real sparse         null,
    FUND12        real sparse         null,
    YTEtMp        real sparse         null,
    TYPSCH12      real sparse         null,
    HELPSE12      real sparse         null,
    YTEtJb        real sparse         null,
    LastJb        real sparse         null,
    Wrking        real sparse         null,
    JbAway        real sparse         null,
    OwnBus        real sparse         null,
    RelBus        real sparse         null,
    EverWk        real sparse         null,
    Caswrk        real sparse         null,
    LeftYr        real sparse         null,
    LeftM         real sparse         null,
    LeftW         real sparse         null,
    LIndD         varchar(80) sparse  null,
    LIndT         varchar(32) sparse  null,
    LOccD         varchar(80) sparse  null,
    LOccT         varchar(32) sparse  null,
    LStat         real sparse         null,
    LManage       real sparse         null,
    LSupvis       real sparse         null,
    LMpnE01       real sparse         null,
    LSolo         real sparse         null,
    LMpnS01       real sparse         null,
    IState        real sparse         null,
    IndD          varchar(80) sparse  null,
    IndT          varchar(32) sparse  null,
    Sector        real sparse         null,
    Sectro03      real sparse         null,
    SocEnt        real sparse         null,
    SecSoc        real sparse         null,
    SecOth        real sparse         null,
    OccT          varchar(32) sparse  null,
    OccD          varchar(80) sparse  null,
    DVOccT        real sparse         null,
    RecJob        real sparse         null,
    Stat          real sparse         null,
    AGWRK         real sparse         null,
    PdWg10        real sparse         null,
    Self1         real sparse         null,
    Self2         real sparse         null,
    Self3         real sparse         null,
    Self4         real sparse         null,
    NITax         real sparse         null,
    HwLng         real sparse         null,
    FifSal        real sparse         null,
    Supvis        real sparse         null,
    Manage        real sparse         null,
    MpnE01        real sparse         null,
    MpnE02        real sparse         null,
    Solo          real sparse         null,
    MpnS01        real sparse         null,
    MpnS02        real sparse         null,
    OneTen        real sparse         null,
    OEmpStat      real sparse         null,
    OMCont        real sparse         null,
    NoCust        real sparse         null,
    FtPtWk        real sparse         null,
    YPTCIA        real sparse         null,
    YPtJob        real sparse         null,
    PTNCre71      real sparse         null,
    PTNCre72      real sparse         null,
    YNotFt        real sparse         null,
    JobTyp        real sparse         null,
    JbTp101       real sparse         null,
    JbTp102       real sparse         null,
    JbTp103       real sparse         null,
    JbTp104       real sparse         null,
    JbTp105       real sparse         null,
    WhyTmp6       real sparse         null,
    TemLen        real sparse         null,
    ConMpY        real sparse         null,
    ConSEY        real sparse         null,
    ConMon        real sparse         null,
    HowGet        real sparse         null,
    CONPRE        real sparse         null,
    CONPRY        real sparse         null,
    CONPRM        real sparse         null,
    CONPRR        real sparse         null,
    TmpCon        real sparse         null,
    WRKLNG1       real sparse         null,
    WRKLNG2       real sparse         null,
    WRKLNG3       real sparse         null,
    WRKLNG4       real sparse         null,
    WRKLNG5       real sparse         null,
    WRKLNG6       real sparse         null,
    WRKLNG7       real sparse         null,
    MAINRET       real sparse         null,
    TmpPay        real sparse         null,
    RedPaid       real sparse         null,
    RedYL13       real sparse         null,
    HthDis        real sparse         null,
    HthRet        real sparse         null,
    HthRes        real sparse         null,
    RedAny        real sparse         null,
    RedYRs        real sparse         null,
    HthOth        real sparse         null,
    RedStat       real sparse         null,
    RedMpNo       real sparse         null,
    RdMpNo2       real sparse         null,
    RedMpN        real sparse         null,
    RedClos       real sparse         null,
    RedP1         real sparse         null,
    RedP2         real sparse         null,
    RedP3         real sparse         null,
    RedInd        real sparse         null,
    RedOcc        real sparse         null,
    RdIndD        varchar(80) sparse  null,
    RdIndT        varchar(32) sparse  null,
    RdOccT        varchar(32) sparse  null,
    RdOccD        varchar(80) sparse  null,
    Home          real sparse         null,
    EvHm98        real sparse         null,
    HomeD1        real sparse         null,
    HomeD2        real sparse         null,
    HomeD3        real sparse         null,
    TeleQA        real sparse         null,
    TeleQB        real sparse         null,
    AtFrom        real sparse         null,
    SmeSit        real sparse         null,
    WkTown        varchar(24) sparse  null,
    WkCty         varchar(24) sparse  null,
    WkPl99        real sparse         null,
    WkAbrC        real sparse         null,
    TrvTme        real sparse         null,
    TrvMth        real sparse         null,
    TrvDrv        real sparse         null,
    HWW4WK        real sparse         null,
    HWWRET        real sparse         null,
    ActWkDy1      real sparse         null,
    ActWkDy2      real sparse         null,
    ActWkDy3      real sparse         null,
    ActWkDy4      real sparse         null,
    ActWkDy5      real sparse         null,
    ActWkDy6      real sparse         null,
    ActWkDy7      real sparse         null,
    ActLow        real sparse         null,
    ActHgh        real sparse         null,
    IllWk         real sparse         null,
    IllDays1      real sparse         null,
    IllDays2      real sparse         null,
    IllDays3      real sparse         null,
    IllDays4      real sparse         null,
    IllDays5      real sparse         null,
    IllDays6      real sparse         null,
    IllDays7      real sparse         null,
    IllLow        real sparse         null,
    IllHgh        real sparse         null,
    ILL1Pd        real sparse         null,
    IL1Bef        real sparse         null,
    ILLNE11       real sparse         null,
    IL2Bef        real sparse         null,
    ILLFst11      real sparse         null,
    ILLSt         real sparse         null,
    ILNxSm        real sparse         null,
    ILLNxt11      real sparse         null,
    EverOT        real sparse         null,
    TotUs1        real sparse         null,
    UsuHr         real sparse         null,
    POtHr         real sparse         null,
    UOtHr         real sparse         null,
    TotUs2        real sparse         null,
    TotAc1        real sparse         null,
    ActHr         real sparse         null,
    ActPOt        real sparse         null,
    ActUOt        real sparse         null,
    TotAc2        real sparse         null,
    YLess6        real sparse         null,
    MatLve        real sparse         null,
    YMore         real sparse         null,
    VaryHr        real sparse         null,
    ShftWk99      real sparse         null,
    ShfTyp        real sparse         null,
    Flex101       real sparse         null,
    Flex102       real sparse         null,
    Flex103       real sparse         null,
    LssOth        real sparse         null,
    DaysPZ        real sparse         null,
    UsuWrkM1      real sparse         null,
    UsuWrkM2      real sparse         null,
    UsuWrkM3      real sparse         null,
    UsuWrkM4      real sparse         null,
    EvEve         real sparse         null,
    EVENG         real sparse         null,
    EvNght        real sparse         null,
    NIGHT         real sparse         null,
    UsuWrk1       real sparse         null,
    UsuWrk2       real sparse         null,
    UsuWrk3       real sparse         null,
    EvDay         real sparse         null,
    WchDay1       real sparse         null,
    WchDay2       real sparse         null,
    WchDay3       real sparse         null,
    WchDay4       real sparse         null,
    WchDay5       real sparse         null,
    WchDay6       real sparse         null,
    WchDay7       real sparse         null,
    EvSat         real sparse         null,
    SATDY         real sparse         null,
    EvSun         real sparse         null,
    SUNDY         real sparse         null,
    Hols          real sparse         null,
    HolsB         real sparse         null,
    BHolChk       real sparse         null,
    BHolCor       real sparse         null,
    BHolPlc       real sparse         null,
    Bank          real sparse         null,
    BnkH1101      real sparse         null,
    BnkH1102      real sparse         null,
    BnkH1103      real sparse         null,
    BnkH1104      real sparse         null,
    BnkH1105      real sparse         null,
    BnkH1106      real sparse         null,
    BnkH1107      real sparse         null,
    BnkH1108      real sparse         null,
    BnkH1109      real sparse         null,
    BnkH1110      real sparse         null,
    BnkH1111      real sparse         null,
    BnkHolF       real sparse         null,
    BHPaid        real sparse         null,
    BHNotA        real sparse         null,
    BHNotB        real sparse         null,
    BHNotC        real sparse         null,
    [Union]       real sparse         null,
    TUPres        real sparse         null,
    TUCov         real sparse         null,
    LIndD2        varchar(80) sparse  null,
    LIndT2        varchar(32) sparse  null,
    LOccD2        varchar(80) sparse  null,
    LOccT2        varchar(32) sparse  null,
    LStat2        real sparse         null,
    LManag2       real sparse         null,
    LSupvis2      real sparse         null,
    LMpnES01      real sparse         null,
    LSolo2        real sparse         null,
    LMpnSS01      real sparse         null,
    SecJob        real sparse         null,
    Y2Job         real sparse         null,
    JobTyp2       real sparse         null,
    Jb2T101       real sparse         null,
    Jb2T102       real sparse         null,
    Jb2T103       real sparse         null,
    Jb2T104       real sparse         null,
    Jb2T105       real sparse         null,
    IndD2         varchar(80) sparse  null,
    IndT2         varchar(32) sparse  null,
    OccT2         varchar(32) sparse  null,
    OccD2         varchar(80) sparse  null,
    RecJb2        real sparse         null,
    Stat2         real sparse         null,
    PdWg102       real sparse         null,
    Self21        real sparse         null,
    Self22        real sparse         null,
    Self23        real sparse         null,
    Self24        real sparse         null,
    NITax2        real sparse         null,
    Supvis2       real sparse         null,
    Manag2        real sparse         null,
    MpnES01       real sparse         null,
    MpnES02       real sparse         null,
    Solo2         real sparse         null,
    MpnSS01       real sparse         null,
    MpnSS02       real sparse         null,
    OEmpStat2     real sparse         null,
    Acthr2        real sparse         null,
    Home2         real sparse         null,
    WkTow2        varchar(24) sparse  null,
    WkCty2        varchar(24) sparse  null,
    WkPl299       real sparse         null,
    DifJob        real sparse         null,
    AddJob        real sparse         null,
    LookM111      real sparse         null,
    LookM112      real sparse         null,
    LookM113      real sparse         null,
    PrefHr        real sparse         null,
    LesPay        real sparse         null,
    UndEmp        real sparse         null,
    UndHrs        real sparse         null,
    UndY981       real sparse         null,
    UndY982       real sparse         null,
    UndY983       real sparse         null,
    UndY984       real sparse         null,
    UndY985       real sparse         null,
    UndY986       real sparse         null,
    UndY987       real sparse         null,
    UndY988       real sparse         null,
    UndY989       real sparse         null,
    UndSt         real sparse         null,
    ExtOth        varchar(104) sparse null,
    LesPay2       real sparse         null,
    LesPay3       real sparse         null,
    OvHrs         real sparse         null,
    Look4         real sparse         null,
    LkYt4         real sparse         null,
    Wait          real sparse         null,
    JobBeg        real sparse         null,
    LikeWk        real sparse         null,
    NoLoWa01      real sparse         null,
    NoLoWa02      real sparse         null,
    NoLoWa03      real sparse         null,
    NoLoWa04      real sparse         null,
    NoLoWa05      real sparse         null,
    NoLoWa06      real sparse         null,
    NoLoWa07      real sparse         null,
    NoLoWa08      real sparse         null,
    NoLoWa09      real sparse         null,
    NoLoWa10      real sparse         null,
    NoLWM         real sparse         null,
    NoLWF         real sparse         null,
    NWNCre1       real sparse         null,
    NWNCre2       real sparse         null,
    FutWk         real sparse         null,
    FWkWen        real sparse         null,
    LkSelA        real sparse         null,
    LkSelC        real sparse         null,
    LkFtPA        real sparse         null,
    LkFtPC        real sparse         null,
    AxPA          real sparse         null,
    AxPB          real sparse         null,
    AxFA          real sparse         null,
    AxFB          real sparse         null,
    MethMp01      real sparse         null,
    MethMp02      real sparse         null,
    MethMp03      real sparse         null,
    MethMp04      real sparse         null,
    MethMp05      real sparse         null,
    MethMp06      real sparse         null,
    MethMp07      real sparse         null,
    MethMp08      real sparse         null,
    MethMp09      real sparse         null,
    MethMp10      real sparse         null,
    MethMp11      real sparse         null,
    MethSE1       real sparse         null,
    MethSE2       real sparse         null,
    MethSE3       real sparse         null,
    MethSE4       real sparse         null,
    MethSE5       real sparse         null,
    MethSE6       real sparse         null,
    MethAl01      real sparse         null,
    MethAl02      real sparse         null,
    MethAl03      real sparse         null,
    MethAl04      real sparse         null,
    MethAl05      real sparse         null,
    MethAl06      real sparse         null,
    MethAl07      real sparse         null,
    MethAl08      real sparse         null,
    MethAl09      real sparse         null,
    MethAl10      real sparse         null,
    MethAl11      real sparse         null,
    MethAl12      real sparse         null,
    MethAl13      real sparse         null,
    MethAl14      real sparse         null,
    MainMe        real sparse         null,
    MainMA        real sparse         null,
    MainMs        real sparse         null,
    MethM         real sparse         null,
    Start         real sparse         null,
    YStart        real sparse         null,
    LkTimA        real sparse         null,
    LLkTimA       real sparse         null,
    LkTimB        real sparse         null,
    Befor         real sparse         null,
    SttBen        real sparse         null,
    Benfts        real sparse         null,
    TpBn1301      real sparse         null,
    TpBn1302      real sparse         null,
    TpBn1303      real sparse         null,
    TpBn1304      real sparse         null,
    TpBn1305      real sparse         null,
    TpBn1306      real sparse         null,
    TpBn1307      real sparse         null,
    TpBn1308      real sparse         null,
    TpBn1309      real sparse         null,
    TpBn1310      real sparse         null,
    BenOth        varchar(256) sparse null,
    UnEmBn1       real sparse         null,
    UnEmBn2       real sparse         null,
    UCredit       real sparse         null,
    JSATyp        real sparse         null,
    JSADur        real sparse         null,
    IncSup        real sparse         null,
    DisBen1       real sparse         null,
    DisBen2       real sparse         null,
    DisBen3       real sparse         null,
    DisBen4       real sparse         null,
    DisBen5       real sparse         null,
    DisBen6       real sparse         null,
    DisBen7       real sparse         null,
    DisBen8       real sparse         null,
    PenBn131      real sparse         null,
    PenBn132      real sparse         null,
    PenBn133      real sparse         null,
    HsngGB1       real sparse         null,
    HsngGB2       real sparse         null,
    MarrCohab     real sparse         null,
    MCNum         real sparse         null,
    OYCirc        real sparse         null,
    OYSInd        real sparse         null,
    OYIndD        varchar(80) sparse  null,
    OYIndT        varchar(32) sparse  null,
    OYSOcc        real sparse         null,
    OYOccT        varchar(32) sparse  null,
    OYOccD        varchar(80) sparse  null,
    OYStat        real sparse         null,
    OYSupvi       real sparse         null,
    Oymnge        real sparse         null,
    OYSolo        real sparse         null,
    OYMPE01       real sparse         null,
    OYMPE02       real sparse         null,
    OYMPS01       real sparse         null,
    OYMPS02       real sparse         null,
    OYOEmpStat    real sparse         null,
    OYFtPt        real sparse         null,
    SubjQ         varchar(152) sparse null,
    SubCode       varchar(8) sparse   null,
    Subqal        varchar(152) sparse null,
    Subno         real sparse         null,
    SubjQ2        varchar(152) sparse null,
    SubCode2      varchar(8) sparse   null,
    Subqal2       varchar(152) sparse null,
    Subno2        real sparse         null,
    SubjQ3        varchar(152) sparse null,
    SubCode3      varchar(8) sparse   null,
    Subqal3       varchar(152) sparse null,
    Subno3        real sparse         null,
    SubjQ4        varchar(152) sparse null,
    SubCode4      varchar(8) sparse   null,
    Subqal4       varchar(152) sparse null,
    Subno4        real sparse         null,
    SubjQ5        varchar(152) sparse null,
    SubCode5      varchar(8) sparse   null,
    Subqal5       varchar(152) sparse null,
    Subno5        real sparse         null,
    SubjQ6        varchar(152) sparse null,
    SubCode6      varchar(8) sparse   null,
    Subqal6       varchar(152) sparse null,
    Subno6        real sparse         null,
    SubjQ7        varchar(152) sparse null,
    SubCode7      varchar(8) sparse   null,
    Subqal7       varchar(152) sparse null,
    Subno7        real sparse         null,
    SubjQ8        varchar(152) sparse null,
    SubCode8      varchar(8) sparse   null,
    Subqal8       varchar(152) sparse null,
    Subno8        real sparse         null,
    FORQUAL       real sparse         null,
    QLFOR111      real sparse         null,
    QLFOR112      real sparse         null,
    QLFOR113      real sparse         null,
    QLFOR114      real sparse         null,
    QLFOR115      real sparse         null,
    QLFOR116      real sparse         null,
    QualUK        real sparse         null,
    QualRe        real sparse         null,
    ForTyp11      real sparse         null,
    FORSUB        varchar(256) sparse null,
    QULCH111      real sparse         null,
    QULCH112      real sparse         null,
    QULCH113      real sparse         null,
    QULCH114      real sparse         null,
    QULCH115      real sparse         null,
    QULCH116      real sparse         null,
    SCQUAL01      real sparse         null,
    SCQUAL02      real sparse         null,
    SCQUAL03      real sparse         null,
    SCQUAL04      real sparse         null,
    SCQUAL05      real sparse         null,
    SCQUAL06      real sparse         null,
    SCQUAL07      real sparse         null,
    SCQUAL08      real sparse         null,
    SCQUAL09      real sparse         null,
    SCQUAL10      real sparse         null,
    SCQUAL11      real sparse         null,
    SCQUAL12      real sparse         null,
    SCQUAL13      real sparse         null,
    SCQUAL14      real sparse         null,
    SCQUAL15      real sparse         null,
    SCQUAL16      real sparse         null,
    SCQUAL17      real sparse         null,
    SCQUAL18      real sparse         null,
    SCQUAL19      real sparse         null,
    SCQUAL20      real sparse         null,
    SCQUAL21      real sparse         null,
    SCQUAL22      real sparse         null,
    SCQUAL23      real sparse         null,
    SCQUAL24      real sparse         null,
    SCQUAL25      real sparse         null,
    UNIQUAL01     real sparse         null,
    UNIQUAL02     real sparse         null,
    UNIQUAL03     real sparse         null,
    UNIQUAL04     real sparse         null,
    UNIQUAL05     real sparse         null,
    UNIQUAL06     real sparse         null,
    UNIQUAL07     real sparse         null,
    UNIQUAL08     real sparse         null,
    UNIQUAL09     real sparse         null,
    UNIQUAL10     real sparse         null,
    UNIQUAL11     real sparse         null,
    UNIQUAL12     real sparse         null,
    UNIQUAL13     real sparse         null,
    UNIQUAL14     real sparse         null,
    UNIQUAL15     real sparse         null,
    UNIQUAL16     real sparse         null,
    UNIQUAL17     real sparse         null,
    UNIQUAL18     real sparse         null,
    UNIQUAL19     real sparse         null,
    UNIQUAL20     real sparse         null,
    UNIQUAL21     real sparse         null,
    UNIQUAL22     real sparse         null,
    UNIQUAL23     real sparse         null,
    UNIQUAL24     real sparse         null,
    UNIQUAL25     real sparse         null,
    UNIQUAL26     real sparse         null,
    UNIQUAL27     real sparse         null,
    UNIQUAL28     real sparse         null,
    UNIQUAL29     real sparse         null,
    UNIQUAL30     real sparse         null,
    UNIQUAL31     real sparse         null,
    WOQUAL01      real sparse         null,
    WOQUAL02      real sparse         null,
    WOQUAL03      real sparse         null,
    WOQUAL04      real sparse         null,
    WOQUAL05      real sparse         null,
    WOQUAL06      real sparse         null,
    WOQUAL07      real sparse         null,
    WOQUAL08      real sparse         null,
    WOQUAL09      real sparse         null,
    WOQUAL10      real sparse         null,
    WOQUAL11      real sparse         null,
    WOQUAL12      real sparse         null,
    WOQUAL13      real sparse         null,
    WOQUAL14      real sparse         null,
    WOQUAL15      real sparse         null,
    WOQUAL16      real sparse         null,
    WOQUAL17      real sparse         null,
    WOQUAL18      real sparse         null,
    WOQUAL19      real sparse         null,
    WOQUAL20      real sparse         null,
    WOQUAL21      real sparse         null,
    WOQUAL22      real sparse         null,
    WOQUAL23      real sparse         null,
    WOQUAL24      real sparse         null,
    WOQUAL25      real sparse         null,
    WOQUAL26      real sparse         null,
    WOQUAL27      real sparse         null,
    WOQUAL28      real sparse         null,
    WOQUAL29      real sparse         null,
    WOQUAL30      real sparse         null,
    WOQUAL31      real sparse         null,
    GSQUAL01      real sparse         null,
    GSQUAL02      real sparse         null,
    GSQUAL03      real sparse         null,
    GSQUAL04      real sparse         null,
    GSQUAL05      real sparse         null,
    GSQUAL06      real sparse         null,
    GSQUAL07      real sparse         null,
    GSQUAL08      real sparse         null,
    GSQUAL09      real sparse         null,
    GSQUAL10      real sparse         null,
    GSQUAL11      real sparse         null,
    GSQUAL12      real sparse         null,
    GSQUAL13      real sparse         null,
    GSQUAL14      real sparse         null,
    GSQUAL15      real sparse         null,
    GSQUAL16      real sparse         null,
    GSQUAL17      real sparse         null,
    GSQUAL18      real sparse         null,
    GSQUAL19      real sparse         null,
    GSQUAL20      real sparse         null,
    GSQUAL21      real sparse         null,
    GSQUAL22      real sparse         null,
    GSQUAL23      real sparse         null,
    GSQUAL24      real sparse         null,
    GSQUAL25      real sparse         null,
    GSQUAL26      real sparse         null,
    GSQUAL27      real sparse         null,
    GSQUAL28      real sparse         null,
    GSQUAL29      real sparse         null,
    GSQUAL30      real sparse         null,
    GSQUAL31      real sparse         null,
    OTQUAL01      real sparse         null,
    OTQUAL02      real sparse         null,
    OTQUAL03      real sparse         null,
    OTQUAL04      real sparse         null,
    OTQUAL05      real sparse         null,
    OTQUAL06      real sparse         null,
    OTQUAL07      real sparse         null,
    OTQUAL08      real sparse         null,
    OTQUAL09      real sparse         null,
    OTQUAL10      real sparse         null,
    OTQUAL11      real sparse         null,
    OTQUAL12      real sparse         null,
    OTQUAL13      real sparse         null,
    OTQUAL14      real sparse         null,
    OTQUAL15      real sparse         null,
    OTQUAL16      real sparse         null,
    OTQUAL17      real sparse         null,
    OTQUAL18      real sparse         null,
    OTQUAL19      real sparse         null,
    OTQUAL20      real sparse         null,
    OTQUAL21      real sparse         null,
    OTQUAL22      real sparse         null,
    OTQUAL23      real sparse         null,
    OTQUAL24      real sparse         null,
    OTQUAL25      real sparse         null,
    OTQUAL26      real sparse         null,
    OTQUAL27      real sparse         null,
    OTQUAL28      real sparse         null,
    OTQUAL29      real sparse         null,
    OTQUAL30      real sparse         null,
    OTQUAL31      real sparse         null,
    QLYr1101      real sparse         null,
    QLYr1102      real sparse         null,
    QLYr1103      real sparse         null,
    QLYr1104      real sparse         null,
    QLYr1105      real sparse         null,
    QLYr1106      real sparse         null,
    QLYr1107      real sparse         null,
    QLYr1108      real sparse         null,
    QLYr1109      real sparse         null,
    QLYr1110      real sparse         null,
    QLYr1111      real sparse         null,
    IntroLev      real sparse         null,
    Degree71      real sparse         null,
    Degree72      real sparse         null,
    Degree73      real sparse         null,
    Degree74      real sparse         null,
    Degree75      real sparse         null,
    HighO         real sparse         null,
    SubjctN       varchar(64) sparse  null,
    SinComN       real sparse         null,
    SngDegN       varchar(8) sparse   null,
    CmbDegN01     real sparse         null,
    CmbDegN02     real sparse         null,
    CmbDegN03     real sparse         null,
    CmbDegN04     real sparse         null,
    CmbDegN05     real sparse         null,
    CmbDegN06     real sparse         null,
    CmbDegN07     real sparse         null,
    CmbDegN08     real sparse         null,
    CmbDegN09     real sparse         null,
    CmbDegN10     real sparse         null,
    CmbDegN11     real sparse         null,
    CmbDegN12     real sparse         null,
    CmbMainN      real sparse         null,
    FDSUBJ        varchar(64) sparse  null,
    FDSinCom      real sparse         null,
    FDSngDeg      varchar(8) sparse   null,
    FDCMBD01      real sparse         null,
    FDCMBD02      real sparse         null,
    FDCMBD03      real sparse         null,
    FDCMBD04      real sparse         null,
    FDCMBD05      real sparse         null,
    FDCMBD06      real sparse         null,
    FDCMBD07      real sparse         null,
    FDCMBD08      real sparse         null,
    FDCMBD09      real sparse         null,
    FDCMBD10      real sparse         null,
    FDCMBD11      real sparse         null,
    FDCMBD12      real sparse         null,
    FDCmbMa       real sparse         null,
    FDINST        varchar(64) sparse  null,
    UGINST        varchar(8) sparse   null,
    DegCls7       real sparse         null,
    HDSUBJCT      varchar(64) sparse  null,
    HDSINCOM      real sparse         null,
    SNGHD         varchar(8) sparse   null,
    CMBHD01       real sparse         null,
    CMBHD02       real sparse         null,
    CMBHD03       real sparse         null,
    CMBHD04       real sparse         null,
    CMBHD05       real sparse         null,
    CMBHD06       real sparse         null,
    CMBHD07       real sparse         null,
    CMBHD08       real sparse         null,
    CMBHD09       real sparse         null,
    CMBHD10       real sparse         null,
    CMBHD11       real sparse         null,
    CMBHD12       real sparse         null,
    CMBHDMA       real sparse         null,
    HDINST        varchar(64) sparse  null,
    PGINST        varchar(8) sparse   null,
    CRYDEG        real sparse         null,
    Teach41       real sparse         null,
    Teach42       real sparse         null,
    Teach43       real sparse         null,
    Teach44       real sparse         null,
    Teach45       real sparse         null,
    Teach46       real sparse         null,
    NumAL         real sparse         null,
    NumAS         real sparse         null,
    TypHST1       real sparse         null,
    TypHST2       real sparse         null,
    TypHST3       real sparse         null,
    TypHST4       real sparse         null,
    TypHST5       real sparse         null,
    AdvHST        real sparse         null,
    HST           real sparse         null,
    WlshBc8       real sparse         null,
    QGCSE41       real sparse         null,
    QGCSE42       real sparse         null,
    QGCSE43       real sparse         null,
    QGCSE44       real sparse         null,
    QGCSE45       real sparse         null,
    GCSE41        real sparse         null,
    GCSE42        real sparse         null,
    GCSE43        real sparse         null,
    GCSE44        real sparse         null,
    GCSE45        real sparse         null,
    NumOl5        real sparse         null,
    MeGCSE        real sparse         null,
    NumOl5O       real sparse         null,
    NumOl5F       real sparse         null,
    QDipTyp       real sparse         null,
    VOCYRA        real sparse         null,
    BTE11         real sparse         null,
    BTACD         real sparse         null,
    BTLEV         real sparse         null,
    BTSUBJ        varchar(256) sparse null,
    BTCTH111      real sparse         null,
    BTCTH112      real sparse         null,
    BTCTH113      real sparse         null,
    BTCTH114      real sparse         null,
    BTCOTLA1      real sparse         null,
    BTCOTLA2      real sparse         null,
    BTCOTLA3      real sparse         null,
    BTCOTLB1      real sparse         null,
    BTCOTLB2      real sparse         null,
    BTCOTLB3      real sparse         null,
    BTCOTLB4      real sparse         null,
    BTCOTLB5      real sparse         null,
    BTCOTLB6      real sparse         null,
    BTCOTLB7      real sparse         null,
    BTCOTLB8      real sparse         null,
    BTCOTLB9      real sparse         null,
    VOCYRB        real sparse         null,
    SCTVC11       real sparse         null,
    SCACD         real sparse         null,
    SCLEV         real sparse         null,
    SCSUBJ        varchar(256) sparse null,
    STCOT111      real sparse         null,
    STCOT112      real sparse         null,
    STCOT113      real sparse         null,
    STCOT114      real sparse         null,
    STCOT115      real sparse         null,
    STCOTLA1      real sparse         null,
    STCOTLA2      real sparse         null,
    STCOTLA3      real sparse         null,
    STCOTLB1      real sparse         null,
    STCOTLB2      real sparse         null,
    STCOTLB3      real sparse         null,
    STCOTLB4      real sparse         null,
    STCOTLB5      real sparse         null,
    STCOTLB6      real sparse         null,
    STCOTLB7      real sparse         null,
    STCOTLB8      real sparse         null,
    STCOTLB9      real sparse         null,
    VOCYRC        real sparse         null,
    RSA11         real sparse         null,
    RSACD         real sparse         null,
    RSLEV         real sparse         null,
    RSASUBJ       varchar(256) sparse null,
    RSAOT111      real sparse         null,
    RSAOT112      real sparse         null,
    RSAOT113      real sparse         null,
    RSAOT114      real sparse         null,
    RSAOTLA1      real sparse         null,
    RSAOTLA2      real sparse         null,
    RSAOTLA3      real sparse         null,
    RSAOTLB1      real sparse         null,
    RSAOTLB2      real sparse         null,
    RSAOTLB3      real sparse         null,
    RSAOTLB4      real sparse         null,
    RSAOTLB5      real sparse         null,
    RSAOTLB6      real sparse         null,
    RSAOTLB7      real sparse         null,
    RSAOTLB8      real sparse         null,
    RSAOTLB9      real sparse         null,
    VOCYRD        real sparse         null,
    CaG11         real sparse         null,
    CAGACD        real sparse         null,
    CAGLEV        real sparse         null,
    CGSUBJ        varchar(256) sparse null,
    CaGOT111      real sparse         null,
    CaGOT112      real sparse         null,
    CaGOT113      real sparse         null,
    CaGOTLA1      real sparse         null,
    CaGOTLA2      real sparse         null,
    CaGOTLA3      real sparse         null,
    CAGOTLB1      real sparse         null,
    CAGOTLB2      real sparse         null,
    CAGOTLB3      real sparse         null,
    CAGOTLB4      real sparse         null,
    CAGOTLB5      real sparse         null,
    CAGOTLB6      real sparse         null,
    CAGOTLB7      real sparse         null,
    CAGOTLB8      real sparse         null,
    CAGOTLB9      real sparse         null,
    QGNVQ         real sparse         null,
    VOCYRE        real sparse         null,
    GNVQ11        real sparse         null,
    GNACD         real sparse         null,
    GNLEV         real sparse         null,
    GNVQSUBJ      varchar(256) sparse null,
    GNVQO111      real sparse         null,
    GNVQO112      real sparse         null,
    GNVQO113      real sparse         null,
    GNVQO114      real sparse         null,
    GNVQO115      real sparse         null,
    GNVQOLA1      real sparse         null,
    GNVQOLA2      real sparse         null,
    GNVQOLA3      real sparse         null,
    GNVQOLB1      real sparse         null,
    GNVQOLB2      real sparse         null,
    GNVQOLB3      real sparse         null,
    GNVQOLB4      real sparse         null,
    GNVQOLB5      real sparse         null,
    GNVQOLB6      real sparse         null,
    GNVQOLB7      real sparse         null,
    GNVQOLB8      real sparse         null,
    GNVQOLB9      real sparse         null,
    NVQSVQ        real sparse         null,
    VOCYRF        real sparse         null,
    NVQ11         real sparse         null,
    NVACD         real sparse         null,
    NVLEV         real sparse         null,
    NVQSUBJ       varchar(256) sparse null,
    NVQO111       real sparse         null,
    NVQO112       real sparse         null,
    NVQO113       real sparse         null,
    NVQO114       real sparse         null,
    NVQO115       real sparse         null,
    NVQO116       real sparse         null,
    NVOTLEA1      real sparse         null,
    NVOTLEA2      real sparse         null,
    NVOTLEA3      real sparse         null,
    NVOTLEB1      real sparse         null,
    NVOTLEB2      real sparse         null,
    NVOTLEB3      real sparse         null,
    NVOTLEB4      real sparse         null,
    NVOTLEB5      real sparse         null,
    NVOTLEB6      real sparse         null,
    NVOTLEB7      real sparse         null,
    NVOTLEB8      real sparse         null,
    NVOTLEB9      real sparse         null,
    NVQun         real sparse         null,
    VOCYRG        real sparse         null,
    QCFACD        real sparse         null,
    QCFLEV        real sparse         null,
    QCFSUBJ       varchar(256) sparse null,
    QCFOTHA1      real sparse         null,
    QCFOTHA2      real sparse         null,
    QCFOTHA3      real sparse         null,
    QCFOTHB1      real sparse         null,
    QCFOTHB2      real sparse         null,
    QCFOTHB3      real sparse         null,
    QCFOTHB4      real sparse         null,
    QCFOTHB5      real sparse         null,
    QCFOTHB6      real sparse         null,
    QCFOTHB7      real sparse         null,
    QCFOTHB8      real sparse         null,
    QCFOTHB9      real sparse         null,
    TpQl111       real sparse         null,
    TpQl112       real sparse         null,
    TpQl113       real sparse         null,
    OthQu91       real sparse         null,
    OthQu92       real sparse         null,
    OthQu93       real sparse         null,
    OthQu94       real sparse         null,
    OthQu95       real sparse         null,
    VOCYRH        real sparse         null,
    OTHQAL11      varchar(256) sparse null,
    OTHQLEV       real sparse         null,
    QalPl11       real sparse         null,
    VocQPl11      real sparse         null,
    YerQal1       real sparse         null,
    YerQal2       real sparse         null,
    YerQal3       real sparse         null,
    WchQGot1      real sparse         null,
    WchQGot2      real sparse         null,
    WchQGot3      real sparse         null,
    WchQGot4      real sparse         null,
    WchQGot5      real sparse         null,
    WchQGot6      real sparse         null,
    WchQGot7      real sparse         null,
    WchQGot8      real sparse         null,
    DVQual01      real sparse         null,
    DVQual02      real sparse         null,
    DVQual03      real sparse         null,
    DVQual04      real sparse         null,
    DVQual05      real sparse         null,
    DVQual06      real sparse         null,
    DVQual07      real sparse         null,
    DVQual08      real sparse         null,
    DVQual09      real sparse         null,
    DVQual10      real sparse         null,
    DVQual11      real sparse         null,
    DVQual12      real sparse         null,
    QHighY        varchar(152) sparse null,
    LAppD         varchar(80) sparse  null,
    LAppT         varchar(32) sparse  null,
    EdAge         real sparse         null,
    QulNow        real sparse         null,
    QulHi11       real sparse         null,
    DegNow        real sparse         null,
    HghNow        real sparse         null,
    TcNw11        real sparse         null,
    TCNWACD       real sparse         null,
    TCNWLEV       real sparse         null,
    SCNow11       real sparse         null,
    SCNWACD       real sparse         null,
    SCNWLEV       real sparse         null,
    DipTyp        real sparse         null,
    OCRN11        real sparse         null,
    OCRNACD       real sparse         null,
    OCRNLEV       real sparse         null,
    CGNw11        real sparse         null,
    CGNWACD       real sparse         null,
    CGNWLEV       real sparse         null,
    HSTNow        real sparse         null,
    WBac          real sparse         null,
    NVQKn2        real sparse         null,
    NVQLe11       real sparse         null,
    NVNWACD       real sparse         null,
    NVNWLEV       real sparse         null,
    QCFNOW        real sparse         null,
    QCFLVNW       real sparse         null,
    CurSub        varchar(152) sparse null,
    CurCode       varchar(8) sparse   null,
    CurQal        varchar(152) sparse null,
    Enroll        real sparse         null,
    Attend        real sparse         null,
    Course        real sparse         null,
    EdIns11       real sparse         null,
    APPR12        real sparse         null,
    APPRCURR      real sparse         null,
    AppSam        real sparse         null,
    AppD          varchar(80) sparse  null,
    AppT          varchar(32) sparse  null,
    AppInD        varchar(80) sparse  null,
    AppInT        varchar(32) sparse  null,
    APPST12       real sparse         null,
    APPRLEV       real sparse         null,
    Ref3Mths      real sparse         null,
    Ref3Day       real sparse         null,
    Ref3Mnth      varchar(16) sparse  null,
    Ed13Wk        real sparse         null,
    Ed4Wk         real sparse         null,
    Futur13       real sparse         null,
    Futur4        real sparse         null,
    JobEd         real sparse         null,
    TrnOpp11      real sparse         null,
    JobTrn        real sparse         null,
    TSte10        real sparse         null,
    TrNI10        real sparse         null,
    TFee101       real sparse         null,
    TFee102       real sparse         null,
    TFee103       real sparse         null,
    TFee104       real sparse         null,
    TFee105       real sparse         null,
    FeeIr1        real sparse         null,
    FeeIr2        real sparse         null,
    FeeIr3        real sparse         null,
    FeeIr4        real sparse         null,
    FeeIr5        real sparse         null,
    TrnLen        real sparse         null,
    TrHr11        real sparse         null,
    TrOnJB        real sparse         null,
    NFE13WK       real sparse         null,
    NFE4WK        real sparse         null,
    TAUT4WK       real sparse         null,
    T4Purp        real sparse         null,
    T4Work        real sparse         null,
    TAUT3M        real sparse         null,
    TSUBJ4WK      varchar(104) sparse null,
    TSUB4Cod      varchar(8) sparse   null,
    TSUBJ3M       varchar(104) sparse null,
    TSUB3Cod      varchar(8) sparse   null,
    TautHrs       real sparse         null,
    TLRN4WK       real sparse         null,
    TLRN3M        real sparse         null,
    Neets         real sparse         null,
    HPrMb         real sparse         null,
    HPrMb2        real sparse         null,
    AccCalc       real sparse         null,
    QHealth1      real sparse         null,
    LngLst        real sparse         null,
    LimitK        real sparse         null,
    LimitA        real sparse         null,
    Dintro        real sparse         null,
    DisLmK        real sparse         null,
    DisLmA        real sparse         null,
    DOnset        real sparse         null,
    DCause        real sparse         null,
    WkSSEmp       real sparse         null,
    DisMobl       real sparse         null,
    AsistPv       real sparse         null,
    AsistNd       real sparse         null,
    AsisFm1       real sparse         null,
    AsisFm2       real sparse         null,
    AsisFm3       real sparse         null,
    AsisFm4       real sparse         null,
    AsisFm5       real sparse         null,
    AsisFm6       real sparse         null,
    AsisFm7       real sparse         null,
    AsisFm8       real sparse         null,
    Heal01        real sparse         null,
    Heal02        real sparse         null,
    Heal03        real sparse         null,
    Heal04        real sparse         null,
    Heal05        real sparse         null,
    Heal06        real sparse         null,
    Heal07        real sparse         null,
    Heal08        real sparse         null,
    Heal09        real sparse         null,
    Heal10        real sparse         null,
    Heal11        real sparse         null,
    Heal12        real sparse         null,
    Heal13        real sparse         null,
    Heal14        real sparse         null,
    Heal15        real sparse         null,
    Heal16        real sparse         null,
    Heal17        real sparse         null,
    LernD         real sparse         null,
    Health        real sparse         null,
    LimAct        real sparse         null,
    HealYr        real sparse         null,
    HealPB01      real sparse         null,
    HealPB02      real sparse         null,
    HealPB03      real sparse         null,
    HealPB04      real sparse         null,
    HealPB05      real sparse         null,
    HealPB06      real sparse         null,
    HealPB07      real sparse         null,
    HealPB08      real sparse         null,
    HealPB09      real sparse         null,
    HealPB10      real sparse         null,
    LernDB        real sparse         null,
    HealYL        real sparse         null,
    Accdnt        real sparse         null,
    Road          real sparse         null,
    WchJb         real sparse         null,
    GoBack        real sparse         null,
    GoBck9        real sparse         null,
    TimeDays      varchar(16) sparse  null,
    TimeCode      varchar(8) sparse   null,
    AccDay4       real sparse         null,
    TypInj        real sparse         null,
    SiteFr1       real sparse         null,
    SiteFr2       real sparse         null,
    SiteFr3       real sparse         null,
    SiteFr4       real sparse         null,
    SiteFr5       real sparse         null,
    SiteFr6       real sparse         null,
    SiteFr7       real sparse         null,
    SiteDi1       real sparse         null,
    SiteDi2       real sparse         null,
    SiteDi3       real sparse         null,
    SiteDi4       real sparse         null,
    SiteDi5       real sparse         null,
    SiteDi6       real sparse         null,
    AccurH1       real sparse         null,
    AccurH2       real sparse         null,
    AccurH3       real sparse         null,
    AccurH4       real sparse         null,
    AccKind       real sparse         null,
    IllWrk        real sparse         null,
    NumIll        real sparse         null,
    TypIll        real sparse         null,
    TmeOff        real sparse         null,
    ILCurr        real sparse         null,
    WchJb3        real sparse         null,
    Aware         real sparse         null,
    ReasOff9      real sparse         null,
    NoBack9       real sparse         null,
    SmokEver      real sparse         null,
    CigNow        real sparse         null,
    RedAct        real sparse         null,
    NRINT         real sparse         null,
    CONCERN       real sparse         null,
    UNDERSTA      real sparse         null,
    AFFECT        real sparse         null,
    INTQ3         real sparse         null,
    WALK          real sparse         null,
    CONFBED       real sparse         null,
    WASH          real sparse         null,
    NOWASH        real sparse         null,
    ACT           real sparse         null,
    NOACT         real sparse         null,
    PAIN          real sparse         null,
    ANXIETY       real sparse         null,
    SCORE1        real sparse         null,
    SCORE2        real sparse         null,
    IncNow        real sparse         null,
    PayDoc        real sparse         null,
    DocNot        varchar(104) sparse null,
    PayIntro      real sparse         null,
    Gross99       real sparse         null,
    GrsExp        real sparse         null,
    GrsPrd        real sparse         null,
    BandG         varchar(8) sparse   null,
    UsGrs99       real sparse         null,
    UsuGPay       real sparse         null,
    UsBandG       varchar(8) sparse   null,
    Net99         real sparse         null,
    NetPrd        real sparse         null,
    BandN         varchar(8) sparse   null,
    IncChk        real sparse         null,
    UsNet99       real sparse         null,
    UsuNPay       real sparse         null,
    UsBandN       varchar(8) sparse   null,
    YVary99       real sparse         null,
    YPayL         real sparse         null,
    PaySSp        real sparse         null,
    YPayM         real sparse         null,
    ErnFilt       real sparse         null,
    Erncm0101     real sparse         null,
    Erncm0102     real sparse         null,
    Erncm0103     real sparse         null,
    Erncm0104     real sparse         null,
    Erncm0105     real sparse         null,
    Erncm0106     real sparse         null,
    Erncm0107     real sparse         null,
    Erncm0108     real sparse         null,
    Erncm0109     real sparse         null,
    Erncm0110     real sparse         null,
    Erncm0111     real sparse         null,
    BonCmp1       real sparse         null,
    BonCmp2       real sparse         null,
    BonCmp3       real sparse         null,
    BonCmp4       real sparse         null,
    Hourly        real sparse         null,
    HrRate        real sparse         null,
    OvrTme        real sparse         null,
    UseSlp        real sparse         null,
    SecSta        real sparse         null,
    Hourly2       real sparse         null,
    HrRate2       real sparse         null,
    SecGro        real sparse         null,
    SecNet        real sparse         null,
    ScNtGa        real sparse         null,
    SecChk        real sparse         null,
    SecEx         real sparse         null,
    SecGA         real sparse         null,
    SecGB         real sparse         null,
    BandG2        varchar(8) sparse   null,
    BandN2        varchar(8) sparse   null,
    IrEnd2        real sparse         null,
    RelBUp        real sparse         null,
    CryFth        real sparse         null,
    CryFSpc       varchar(40) sparse  null,
    CryFFrm       real sparse         null,
    CryMth        real sparse         null,
    CryMSpc       varchar(40) sparse  null,
    CryMFrm       real sparse         null,
    FathEdu       real sparse         null,
    MothEdu       real sparse         null,
    WkOthCry      real sparse         null,
    CrySix        real sparse         null,
    WchCry        varchar(40) sparse  null,
    WchCryFr      real sparse         null,
    ComeUK1       real sparse         null,
    ComeUK2       real sparse         null,
    ComeUK3       real sparse         null,
    ComeUK4       real sparse         null,
    ComeUK5       real sparse         null,
    ComeUKMn      real sparse         null,
    JobInUK       real sparse         null,
    OvrQual       real sparse         null,
    ObSkilM       real sparse         null,
    ObSkilS       real sparse         null,
    ObJobM        real sparse         null,
    ObJobS        real sparse         null,
    LangSkil      real sparse         null,
    LangCour      real sparse         null,
    FindJob       real sparse         null,
    Soc10MU       varchar(8) sparse   null,
    S2kStMU_index real sparse         null,
    Soc2kMU_index varchar(8) sparse   null,
    SerNoMU_index real sparse         null,
    Soc10MC       varchar(8) sparse   null,
    S2kStMC_index real sparse         null,
    Soc2kMC_index varchar(8) sparse   null,
    SerNoMC_index real sparse         null,
    Soc102U       varchar(8) sparse   null,
    S2kSt2U_index real sparse         null,
    Soc2k2U_index varchar(8) sparse   null,
    SerNo2U_index real sparse         null,
    Soc102C       varchar(8) sparse   null,
    S2kSt2C_index real sparse         null,
    Soc2k2C_index varchar(8) sparse   null,
    SerNo2C_index real sparse         null,
    Soc10OY       varchar(8) sparse   null,
    S2kStOY_index real sparse         null,
    Soc2kOY_index varchar(8) sparse   null,
    SerNoOY_index real sparse         null,
    Soc10Rd       varchar(8) sparse   null,
    S2kStRd_index real sparse         null,
    Soc2kRd_index varchar(8) sparse   null,
    SerNoRd_index real sparse         null,
    Soc10AU       varchar(8) sparse   null,
    S2kStAU_index real sparse         null,
    Soc2kAU_index varchar(8) sparse   null,
    SerNoAU_index real sparse         null,
    Soc10AC       varchar(8) sparse   null,
    S2kStAC_index real sparse         null,
    Soc2kAC_index varchar(8) sparse   null,
    SerNoAC_index real sparse         null,
    SearchTxtM    varchar(80) sparse  null,
    SearchTxt2    varchar(80) sparse  null,
    SearchTxtO    varchar(80) sparse  null,
    SearchTxtR    varchar(80) sparse  null,
    SearchTxtA    varchar(80) sparse  null,
    SearchTxtF    varchar(80) sparse  null,
    SearchTxtW    varchar(80) sparse  null,
    Phase         real sparse         null,
    ChangeOccM    real sparse         null,
    ChangeOcc2    real sparse         null,
    EquivOccO     real sparse         null,
    EquivOccR     real sparse         null,
    EquivOccOY    real sparse         null,
    ChangeOccA    real sparse         null,
    CodeIntroM    real sparse         null,
    CodeIntro2    real sparse         null,
    CodeIntroO    real sparse         null,
    CodeIntroR    real sparse         null,
    CodeIntroA    real sparse         null,
    CodeIntroW    real sparse         null,
    Ocod10M       real sparse         null,
    S2kStM_index  real sparse         null,
    Soc2kM_index  varchar(8) sparse   null,
    SerNoM_index  real sparse         null,
    Ocod102       real sparse         null,
    S2kSt2_index  real sparse         null,
    Soc2k2_index  varchar(8) sparse   null,
    SerNo2_index  real sparse         null,
    Ocod10O       real sparse         null,
    S2kStO_index  real sparse         null,
    Soc2kO_index  varchar(8) sparse   null,
    SerNoO_index  real sparse         null,
    Ocod10R       real sparse         null,
    S2kStR_index  real sparse         null,
    Soc2kR_index  varchar(8) sparse   null,
    SerNoR_index  real sparse         null,
    Ocod10A       real sparse         null,
    S2kStA_index  real sparse         null,
    Soc2kA_index  varchar(8) sparse   null,
    SerNoA_index  real sparse         null,
    S2kStW_index  real sparse         null,
    Soc2kW_index  varchar(8) sparse   null,
    SerNoW_index  real sparse         null,
    Ocod2KM       real sparse         null,
    Ocod2K2       real sparse         null,
    Ocod2KO       real sparse         null,
    Ocod2KR       real sparse         null,
    Ocod2KA       real sparse         null,
    SECM          real sparse         null,
    SECFlagM      real sparse         null,
    ES2000M       real sparse         null,
    SECMIES       real sparse         null,
    SEC2          real sparse         null,
    SECFlag2      real sparse         null,
    ES20002       real sparse         null,
    SEC2IES       real sparse         null,
    SECO          real sparse         null,
    SECFlagO      real sparse         null,
    ES2000O       real sparse         null,
    SECOIES       real sparse         null,
    SECR          real sparse         null,
    SECFlagR      real sparse         null,
    ES2000R       real sparse         null,
    SECRIES       real sparse         null,
    ICdM          real sparse         null,
    ICod2007      varchar(16) sparse  null,
    ICod07        real sparse         null,
    ICdC2007      varchar(16) sparse  null,
    ICdC07        real sparse         null,
    IEmpStat      real sparse         null,
    IEmpStatC     real sparse         null,
    IMPSTM        real sparse         null,
    ICd2          real sparse         null,
    ICd22007      varchar(16) sparse  null,
    ICd207        real sparse         null,
    ICC22007      varchar(16) sparse  null,
    ICC207        real sparse         null,
    IEmpStat2     real sparse         null,
    IEmpStat2C    real sparse         null,
    IMPST2        real sparse         null,
    OYIC2007      varchar(16) sparse  null,
    OYICd07       real sparse         null,
    OYIEmpStat    real sparse         null,
    RdIC2007      varchar(16) sparse  null,
    RdICd07       real sparse         null,
    CodChk        real sparse         null,
    IndOut        real sparse         null,
    PERSFLAG      real sparse         null,
    RPERSFLAG     real sparse         null,
    RECALLP       real sparse         null,
    CodeNow       real sparse         null,
    HiHNum        varchar(56) sparse  null,
    IsHIC1        real sparse         null,
    JntEldA       real sparse         null,
    JntEldB       real sparse         null,
    DVHRPNUM      real sparse         null,
    HRPCheck      real sparse         null,
    ShowBen       real sparse         null,
    DVBenU1       real sparse         null,
    DVnumBU       real sparse         null,
    Thanks        real sparse         null,
    ThankE        real sparse         null,
    ThankWvF      real sparse         null,
    ThankEth      real sparse         null,
    Flag75        real sparse         null,
    Thank75a      real sparse         null,
    Thank75b      real sparse         null,
    RecallH       real sparse         null,
    GotPhone      real sparse         null,
    RecPhone      real sparse         null,
    Chk_Num1      real sparse         null,
    PrefNo        real sparse         null,
    Chk_Num2      real sparse         null,
    AltNo         real sparse         null,
    Display       real sparse         null,
    AppointType   real sparse         null,
    WeekDays1     real sparse         null,
    WeekDays2     real sparse         null,
    WeekDays3     real sparse         null,
    WeekDays4     real sparse         null,
    WeekDays5     real sparse         null,
    WeekDays6     real sparse         null,
    AppointTime   real sparse         null,
    TimeStart     real sparse         null,
    TimeEnd       real sparse         null,
    CalSun        real sparse         null,
    MultHh11      real sparse         null,
    MHHType       real sparse         null,
    AddRes        real sparse         null,
    AccSh         real sparse         null,
    ShaLiv        real sparse         null,
    MealSh        real sparse         null,
    Shacook       real sparse         null,
    MltiOld1      real sparse         null,
    MltiOld2      real sparse         null,
    MultiNew      real sparse         null,
    NumHhld       real sparse         null,
    HhldDesc      varchar(24) sparse  null,
    Multhhld      real sparse         null,
    IntIntrp      real sparse         null,
    NonEng        real sparse         null,
    WhLang01      real sparse         null,
    WhLang02      real sparse         null,
    WhLang03      real sparse         null,
    WhLang04      real sparse         null,
    WhLang05      real sparse         null,
    WhLang06      real sparse         null,
    WhLang07      real sparse         null,
    WhLang08      real sparse         null,
    WhLang09      real sparse         null,
    WhLang10      real sparse         null,
    WhLang11      real sparse         null,
    WhlangO       varchar(32) sparse  null,
    WhoTrans1     real sparse         null,
    WhoTrans2     real sparse         null,
    WhoTrans3     real sparse         null,
    WhoTrans4     real sparse         null,
    WhoTrans5     real sparse         null,
    WhoTrans6     real sparse         null,
    NmTrans       real sparse         null,
    Iout1         real sparse         null,
    Iout2         real sparse         null,
    Iout4         real sparse         null,
    ProxPers      real sparse         null,
    AgeCheck      real sparse         null,
    NumFuPer      real sparse         null,
    NumPaPry      real sparse         null,
    NumFuPry      real sparse         null,
    NumPaPer      real sparse         null,
    NumNoElg      real sparse         null,
    NumRefus      real sparse         null,
    NumNonco      real sparse         null,
    NumParls      real sparse         null,
    NumFull       real sparse         null,
    NumInt        real sparse         null,
    NumNotEl      real sparse         null,
    NumSevIn      real sparse         null,
    IndCheck      real sparse         null,
    HarmIntr      real sparse         null,
    Intsome       real sparse         null,
    IntFin        real sparse         null,
    Outsum        real sparse         null,
    IndOut4       real sparse         null,
    Inelig1       real sparse         null,
    Uncer1        real sparse         null,
    NonSum        real sparse         null,
    Ref1          real sparse         null,
    Ref2          real sparse         null,
    Ref3          real sparse         null,
    Refreas1      real sparse         null,
    Refreas2      real sparse         null,
    Refreas3      real sparse         null,
    Nonc1         real sparse         null,
    Nonreas1      real sparse         null,
    Nonreas2      real sparse         null,
    Nonreas3      real sparse         null,
    Othr1         real sparse         null,
    Othr2         real sparse         null,
    Othr3         real sparse         null,
    Hout04        real sparse         null,
    HoutLFS       real sparse         null,
    AnyVisit      real sparse         null,
    RtypHH        real sparse         null,
    RTypOth       varchar(104) sparse null,
    DwellTyp      real sparse         null,
    FloorN        real sparse         null,
    EntryN1       real sparse         null,
    EntryN2       real sparse         null,
    EntryN3       real sparse         null,
    EntryN4       real sparse         null,
    EntryN5       real sparse         null,
    EntryN6       real sparse         null,
    TotTime       real sparse         null,
    Main          real sparse         null,
    IntvLang      real sparse         null,
    FTFphone      real sparse         null,
    Direction     varchar(80) sparse  null,
    BriefSDC1     real sparse         null,
    BriefSDC2     real sparse         null,
    BriefSDC3     real sparse         null,
    Brief1        varchar(80) sparse  null,
    LBrief1       varchar(80) sparse  null,
    Brief2        varchar(80) sparse  null,
    AnyLeft       real sparse         null,
    DoneCode      real sparse         null,
    RefNon        real sparse         null,
    Refuse1       real sparse         null,
    Refuse2       real sparse         null,
    Refuse3       real sparse         null,
    RefOth        varchar(104) sparse null,
    NnCont        real sparse         null,
    NnCOth        varchar(104) sparse null,
    ReIssue       real sparse         null,
    ReOther       varchar(104) sparse null,
    Iss1Int       real sparse         null,
    Iss1HOut      real sparse         null,
    Iss1NC        real sparse         null,
    Iss1CRef      real sparse         null,
    ReIss         real sparse         null,
    HOut          real sparse         null,
    HOutC         real sparse         null,
    HOutDate      real sparse         null,
    CRef          real sparse         null,
    TOIntOut      real sparse         null,
    ChkLet        varchar(8) sparse   null,
    DivAddInd     varchar(8) sparse   null,
    CaseOjectInd  varchar(8) sparse   null,
    GORA          varchar(8) sparse   null,
    CountryCod    varchar(8) sparse   null,
    Wave          varchar(8) sparse   null,
    ChkLet2       varchar(8) sparse   null,
    OAInd         varchar(8) sparse   null,
    URIndEW       varchar(8) sparse   null,
    URIndSc       varchar(8) sparse   null,
    NHSAcc        varchar(8) sparse   null,
    GOR99         varchar(8) sparse   null,
    TelFTF        varchar(8) sparse   null,
    SupVsMU_index varchar(8) sparse   null,
    SupVsMC_index varchar(8) sparse   null,
    SupVs2U_index varchar(8) sparse   null,
    SupVs2C_index varchar(8) sparse   null,
    SupVsOY_index varchar(8) sparse   null,
    SupVsRd_index varchar(8) sparse   null,
    SupVsAU_index varchar(8) sparse   null,
    SupVsAC_index varchar(8) sparse   null,
    SupVsM_index  varchar(8) sparse   null,
    SupVs2_index  varchar(8) sparse   null,
    SupVsO_index  varchar(8) sparse   null,
    SupVsR_index  varchar(8) sparse   null,
    SupVsA_index  varchar(8) sparse   null,
    SupVsW_index  varchar(8) sparse   null,
    BULater       varchar(8) sparse   null,
    FldReg        varchar(8) sparse   null,
    Dteofbth      varchar(8) sparse   null,
    CID96_new     varchar(8) sparse   null,
    LAD96_new     varchar(8) sparse   null,
    PrimaryFirst  real sparse         null,
    UALAD99       varchar(8) sparse   null,
    Urindew_new   varchar(8) sparse   null,
    Urindsc_new   varchar(8) sparse   null,
    Urind         varchar(8) sparse   null,

    cs xml column_set FOR ALL_SPARSE_COLUMNS,

    primary key (file_week, file_month, file_year),

    constraint gb_key
        foreign key (id) references gb_batch_items (id)
            on delete cascade,

    constraint ni_key
        foreign key (id) references ni_batch_item (id)
            on delete cascade
);

create table survey_audit
(
    id             int           not null primary key,
    file_name      varchar(1024) not null index survey_audit_file_name_index,
    file_source    char(2)       not null,
    week           int           null,
    month          int           null,
    year           int           null,
    reference_date datetime      not null,
    num_var_file   int           not null default 0,
    num_var_loaded int           not null default 0,
    num_ob_file    int           not null default 0,
    num_ob_loaded  int           not null default 0,
    status         int           not null,
    message        varchar(1024) null,
    constraint survey_audit_status_values_id_fk
        foreign key (status) references status_values (id)
);


create table users
(
    username varchar(255) not null primary key,
    password varchar(255) not null,
    constraint users_username_uindex
        unique (username)
);

insert into users(username, password)
values ('Admin', '$2a$04$Su7c9o6E9pLaGut2Nv9FqO2ZUbntDmUweOlO/Vj3hczi86qrnbKK2');
