
debug = true

[database]

server = "" # set by environment variables
user = "" # set by environment variables
password = "" # set by environment variables
verbose = false
database = "" # set by environment variables

    [database.pool]

       maxPoolSize = 10
       maxIdleConnections = 2
       maxLifetimeSeconds = 0
