
debug = true

testDirectory = "/home/paul/GolandProjects/pds-go/testdata/"
#testDirectory = "/Users/pauld/GolandProjects/pds-go/testdata/"

[database]

server = "localhost" # set by environment variables
user = "lfs" # set by environment variables
password = "lfs" # set by environment variables
verbose = false
database = "lfs" # set by environment variables

    [database.pool]
       maxPoolSize = 10
       maxIdleConnections = 2
       maxLifetimeSeconds = 0
