
debug = true

[database]

server = "localhost"
user = "ips"
password = "ips"
verbose = false
database = "ips"

    [database.pool]

       maxPoolSize = 10
       maxIdleConnections = 2
       maxLifetimeSeconds = 0
