
debug = true

testDirectory = "/Users/paul/go/src/pds-go/testdata/"
#testDirectory = "/Users/pauld/GolandProjects/pds-go/testdata/"

[database]

server = "" # set by environment variables
user = "" # set by environment variables
password = "" # set by environment variables
verbose = false
database = "" # set by environment variables

    [database.pool]
       maxPoolSize = 10
       maxIdleConnections = 2
       maxLifetimeSeconds = 0
