package types

type Addresses struct {
	Pcd7                string  `db:"pcd7"`
	Tlec99              string  `db:"pcd7"`
	ELWA                float64 `db:"ELWA"`
	SCOTER              string  `db:"SCOTER"`
	Walespca            float64 `db:"Walespca"`
	Ward03              string  `db:"ward03"`
	Scotpca             float64 `db:"scotpca"`
	Ukpca               float64 `db:"ukpca"`
	TTWA07              float64 `db:"TTWA07"`
	Ttwa08              float64 `db:"ttwa08"`
	Pca2010             string  `db:"pca2010"`
	Nuts2               string  `db:"nuts2"`
	Nuts3               string  `db:"nuts3"`
	Nuts4               string  `db:"nuts4"`
	Nuts10              string  `db:"nuts10"`
	Nuts102             string  `db:"nuts102"`
	Nuts103             string  `db:"nuts103"`
	Nuts104             string  `db:"nuts104"`
	Eregn10             string  `db:"eregn10"`
	Eregn103            string  `db:"eregn103"`
	NUTS133             string  `db:"NUTS133"`
	NUTS132             string  `db:"NUTS132"`
	Eregn133            string  `db:"eregn133"`
	Eregn13             string  `db:"eregn13"`
	DEGURBA             float64 `db:"DEGURBA"`
	Dzone1              string  `db:"dzone1"`
	Dzone2              string  `db:"dzone2"`
	Soa1                string  `db:"soa1"`
	Soa2                string  `db:"soa2"`
	Ward05              string  `db:"ward05"`
	Oacode              string  `db:"oacode"`
	Urind               float64 `db:"urind"`
	Urindsul            float64 `db:"urindsul"`
	Lea                 string  `db:"lea"`
	Ward98              string  `db:"ward98"`
	OSLAUA9d            string  `db:"OSLAUA9d"`
	Ctry9d              string  `db:"ctry9d"`
	Casward             string  `db:"casward"`
	Oa11                string  `db:"oa11"`
	CTY                 string  `db:"CTY"`
	LAUA                string  `db:"LAUA"`
	WARD                string  `db:"WARD"`
	CED                 string  `db:"CED"`
	GOR9d               string  `db:"GOR9d"`
	PCON9d              string  `db:"PCON9d"`
	TECLEC9d            string  `db:"TECLEC9d"`
	TTWA9d              string  `db:"TTWA9d"`
	Lau2                string  `db:"lau2"`
	PARK                string  `db:"PARK"`
	LSOA11              string  `db:"LSOA11"`
	MSOA11              string  `db:"MSOA11"`
	CCG                 string  `db:"CCG"`
	RU11IND             string  `db:"RU11IND"`
	OAC11               string  `db:"OAC11"`
	LEP1                string  `db:"LEP1"`
	LEP2                string  `db:"LEP2"`
	IMD                 float64 `db:"IMD"`
	Ru11indsul          float64 `db:"ru11indsul"`
	NUTS163             string  `db:"NUTS163"`
	NUTS162             string  `db:"NUTS162"`
	Eregn163            string  `db:"eregn163"`
	Eregn16             string  `db:"eregn16"`
	METCTY              string  `db:"METCTY"`
	UTLA                string  `db:"UTLA"`
	WIMD2014quintile    float64 `db:"WIMD2014quintile"`
	Decile2015          float64 `db:"decile2015"`
	CombinedAuthorities string  `db:"CombinedAuthorities"`
}
