package types

type Addresses struct {
	Pcd7                string  `db:"pcd7" csv:"pcd7"`
	Tlec99              string  `db:"tlec99" csv:"tlec99"`
	ELWA                float64 `db:"ELWA" csv:"ELWA"`
	SCOTER              string  `db:"SCOTER" csv:"SCOTER"`
	Walespca            float64 `db:"Walespca" csv:"Walespca"`
	Ward03              string  `db:"ward03" csv:"ward03"`
	Scotpca             float64 `db:"scotpca" csv:"scotpca"`
	Ukpca               float64 `db:"ukpca" csv:"ukpca"`
	TTWA07              float64 `db:"TTWA07" csv:"TTWA07"`
	Ttwa08              float64 `db:"ttwa08" csv:"ttwa08"`
	Pca2010             string  `db:"pca2010" csv:"pca2010"`
	Nuts2               string  `db:"nuts2" csv:"nuts2"`
	Nuts3               string  `db:"nuts3" csv:"nuts3"`
	Nuts4               string  `db:"nuts4" csv:"nuts4"`
	Nuts10              string  `db:"nuts10" csv:"nuts10"`
	Nuts102             string  `db:"nuts102" csv:"nuts102"`
	Nuts103             string  `db:"nuts103" csv:"nuts103"`
	Nuts104             string  `db:"nuts104" csv:"nuts104"`
	Eregn10             string  `db:"eregn10" csv:"eregn10"`
	Eregn103            string  `db:"eregn103" csv:"eregn103"`
	NUTS133             string  `db:"NUTS133" csv:"NUTS133"`
	NUTS132             string  `db:"NUTS132" csv:"NUTS132"`
	Eregn133            string  `db:"eregn133" csv:"eregn133"`
	Eregn13             string  `db:"eregn13" csv:"eregn13"`
	DEGURBA             float64 `db:"DEGURBA" csv:"DEGURBA"`
	Dzone1              string  `db:"dzone1" csv:"dzone1"`
	Dzone2              string  `db:"dzone2" csv:"dzone2"`
	Soa1                string  `db:"soa1" csv:"soa1"`
	Soa2                string  `db:"soa2" csv:"soa2"`
	Ward05              string  `db:"ward05" csv:"ward05"`
	Oacode              string  `db:"oacode" csv:"oacode"`
	Urind               float64 `db:"urind" csv:"urind"`
	Urindsul            float64 `db:"urindsul" csv:"urindsul"`
	Lea                 string  `db:"lea" csv:"lea"`
	Ward98              string  `db:"ward98" csv:"ward98"`
	OSLAUA9d            string  `db:"OSLAUA9d" csv:"OSLAUA9d"`
	Ctry9d              string  `db:"ctry9d" csv:"ctry9d"`
	Casward             string  `db:"casward" csv:"casward"`
	Oa11                string  `db:"oa11" csv:"oall"`
	CTY                 string  `db:"CTY" csv:"CTY"`
	LAUA                string  `db:"LAUA" csv:"LAUA"`
	WARD                string  `db:"WARD" csv:"WARD"`
	CED                 string  `db:"CED" csv:"CED"`
	GOR9d               string  `db:"GOR9d" csv:"GOR9d"`
	PCON9d              string  `db:"PCON9d" csv:"PCON9d"`
	TECLEC9d            string  `db:"TECLEC9d" csv:"TECLEC9d"`
	TTWA9d              string  `db:"TTWA9d" csv:"TTWA9d"`
	Lau2                string  `db:"lau2" csv:"lau2"`
	PARK                string  `db:"PARK" csv:"PARK"`
	LSOA11              string  `db:"LSOA11" csv:"LSOA11"`
	MSOA11              string  `db:"MSOA11" csv:"MSOA11"`
	CCG                 string  `db:"CCG" csv:"CCG"`
	RU11IND             string  `db:"RU11IND" csv:"RU11IND"`
	OAC11               string  `db:"OAC11" csv:"OAC11"`
	LEP1                string  `db:"LEP1" csv:"LEP1"`
	LEP2                string  `db:"LEP2" csv:"LEP2"`
	IMD                 float64 `db:"IMD" csv:"IMD"`
	Ru11indsul          float64 `db:"ru11indsul" csv:"ru11indsul"`
	NUTS163             string  `db:"NUTS163" csv:"NUTS163"`
	NUTS162             string  `db:"NUTS162" csv:"NUTS162"`
	Eregn163            string  `db:"eregn163" csv:"eregn163"`
	Eregn16             string  `db:"eregn16" csv:"eregn16"`
	METCTY              string  `db:"METCTY" csv:"METCTY"`
	UTLA                string  `db:"UTLA" csv:"UTLA"`
	WIMD2014quintile    float64 `db:"WIMD2014quintile" csv:"WIMD2014quintile"`
	Decile2015          float64 `db:"decile2015" csv:"decile2015"`
	CombinedAuthorities string  `db:"CombinedAuthorities" csv:"CombinedAuthorities"`
}
